language: cpp

addons:
    packages:
      - cmake
#cache:
#  directories:
#    - clang
#
#matrix:
#  include:
#    - os:        osx
#      osx_image: xcode8.3
#      compiler: clang
#      env: PREC=single
#    - os:        osx
#      osx_image: xcode8.3
#      compiler: clang
#      env: PREC=double
#
#before_install:
#    - export GRIDDIR=`pwd`
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "clang" ]] && [ ! -e clang/bin ]; then wget $CLANG_LINK; tar -xf `basename #$CLANG_LINK`; mkdir clang; mv clang+*/* clang/; fi
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "clang" ]]; then export PATH="${GRIDDIR}/clang/bin:${PATH}"; fi
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "clang" ]]; then export LD_LIBRARY_PATH="${GRIDDIR}/clang/lib:${LD_LIBRARY_PATH}"; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libmpc openssl; fi
#
#install:
#    - export CWD=`pwd`
#    - echo $CWD
#    - export CC=$CC$VERSION
#    - export CXX=$CXX$VERSION
#    - echo $PATH
#    - which autoconf
#    - autoconf  --version
#    - which automake
#    - automake  --version
#    - which $CC
#    - $CC  --version
#    - which $CXX
#    - $CXX --version
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LDFLAGS='-L/usr/local/lib'; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export EXTRACONF='--with-openssl=/usr/local/opt/openssl'; fi

script:
    - mkdir build; cd build
    - cmake ../
    - make
    - bash ../tests/run_tests.sh
